### ISSUE TITLE
C/C++ and Kotlin Support

### ISSUE THREAD

**Issue by Slxe** [y3sh/Intellij-Colors-Sublime-Monokai#16]
Hi! Thanks for putting this together, was wondering if you could add support for C/C++ and Kotlin please!

**Comment by BigPa** [comment]
+1 could you support C/C++ for Clion?

**Comment by y3sh** [comment]
It looks like some of the colors transfer well, but there's still a bit of work here. Could you provide a code sample or sample project to demo the features of C/C++ and Kotlin?

**Comment by comino** [comment]
+1 for Clion port !

**Comment by y3sh** [comment]
Please submit code samples as a pull request. See https://github.com/y3sh/Intellij-Colors-Sublime-Monokai/tree/master/code-samples for other langs.
