### ISSUE TITLE
doesnt work with Intellij 14

### ISSUE THREAD

**Issue by anhnt** [y3sh/Intellij-Colors-Sublime-Monokai#17]
Please consider to make this beautiful theme work with Intellij 14 Ultimate. Thanks

**Comment by y3sh** [comment]
Added support through 15, please test.

**Comment by anhnt** [comment]
still not work with my IntelliJ 14 ultimate. Not sure what happened but after importing jar file, in config/colors there is a SublimeMonokai.xml file but the IDE cant recognize it and nothing happens

**Comment by y3sh** [comment]
![image](https://cloud.githubusercontent.com/assets/1032983/12400636/e98d17cc-bde6-11e5-8e98-3f3d78f69a76.png)

I just tested on 14 and it seems to be ok. Consider packaging the jar like in https://github.com/y3sh/Intellij-Colors-Sublime-Monokai/blob/master/buildjar.sh

**Comment by anhnt** [comment]
Thanks for your help but I believe it wont work on Windows 10. Please consider to make a window version of this beautiful scheme. I really appreciate this!

**Comment by y3sh** [comment]
I tried it in Windows 10 with Intellij 15 and below was the result. It looks like the font support and font smoothing are different. If you have any ideas on how to fix, let me know.

![screen shot 2016-02-02 at 7 59 51 pm](https://cloud.githubusercontent.com/assets/1032983/12770641/ba42bbae-c9e7-11e5-906c-d8b01e0fdf49.png)
