### ISSUE TITLE
The same variable does not display with the same color

### ISSUE THREAD

**Issue by zhanggang807** [y3sh/Intellij-Colors-Sublime-Monokai#18]
IDEA version : 15.0.2

Darcula work well：
![aaaa](https://cloud.githubusercontent.com/assets/4559603/12189449/ab173e1e-b5f8-11e5-8153-8aa91bbeb14d.jpg)

SublimeMonokai does not work：
![image](https://cloud.githubusercontent.com/assets/4559603/12189345/b55541ce-b5f7-11e5-9a6c-18f0261742b5.png)

**Comment by y3sh** [comment]
fixed please test

**Comment by ubuntudroid** [comment]
Nice! Looks good. :)
