### ISSUE TITLE
Generating Jars For Other Sublime Themes

### ISSUE THREAD

**Issue by P0und-cake** [y3sh/Intellij-Colors-Sublime-Monokai#19]
Hi,

First off, I think this is awesome. I recently started using Intellij with the IlluminatedCloud plugin for Salesforce development. Previously I was using Sublime with the MavensMate plugin and I really missed my sublime themes after switching.

My question is, is there any way to generate the jar files for other sublime themes? It would be great if I could do this for any sublime theme.

How did you go about generating that xml file from the theme and from there, the jar file?

**Comment by y3sh** [comment]
Thanks for the good feedback. I didn't convert or generate this theme from Sublime. I actually don't like ST2 or ST3's default themes. I hand-created this theme in Intellij's pref pane based on some pastels from Sublime and some inspiration from other tech sources (see below). 

![st](https://cloud.githubusercontent.com/assets/1032983/12770394/ab253e96-c9e5-11e5-9466-d0df9843fdbd.jpg)

Just as [buildJar.sh](https://github.com/y3sh/Intellij-Colors-Sublime-Monokai/blob/master/buildjar.sh) puts the theme XML in a jar, you can export Intelij prefs as a jar and get the XML back out. I think in IJ 12 or 13 they changed the file extension to something else, but it's still XML inside the prefs jar.
