### ISSUE TITLE
Unsupported Color Scheme Version - SOLVED

### ISSUE THREAD

**Issue by JacobAMason** [y3sh/Intellij-Colors-Sublime-Monokai#21]
"Cannot read scheme SublimeMonokai.xml from '$ROOT_CONFIG$/colors':Unsupported color scheme version: 142"

When I install the jar file, it says it installed fine and that I have to restart, but then I get this error. I tried both downloading the jar and building it myself with the same result.

I've found that a good few people have had this issue and here is how you fix it:
Open the xml file and change the version number from 142 to the major build number version of your Intellij product (I'm using Android Studio, but it works there, too). If you click Help -> About, the major build number is the number before the period. Mine was 141 instead. I changed the number in the xml and it worked fine.

I logged this as an issue here because this is where I first came across the problem and I want others to know how to solve it.

**Comment by jaiwardhan** [comment]
Hey I am using intelliJ Idea 14.1.5, and i have a similar issue with another theme (Sublime Text 2). It shows a similar error. I tried following your steps, but i cannot find the file 'Sublime Text 2.xml' in the application file. How do i remove that?
For reference, the SS is here: [Screenshot](http://imgur.com/a/emVew)

**Comment by JacobAMason** [comment]
@jaiwardhan I think your problem is a bit different. The scheme is unsupported, but for a different reason. I've never seen this error before, but maybe throw the contents of the xml in a gist and we can take a look?

**Comment by jaiwardhan** [comment]
well I cannot find the xml for the theme anywhere. Although this is not a problem for my IDE, but its annoying as whenever i start the IDE this pops up. Is there a place from which IntelliJ picks up the list of all installed themes, and tries to read it but fails since there is no file present? Probably we can remove the entry from there?

**Comment by JacobAMason** [comment]
You should be able to change the editor colors by going to `Settings > Editor > Colors & Fonts`. See if 'Default` is selected or something else.

**Comment by jaiwardhan** [comment]
Default is present there, can't find sublime text 2 there again. It happens only when the IDE loads. Probably it tries to load all the installed ones at startup and fails to find this one.

**Comment by JacobAMason** [comment]
That's possible. I don't see that theme in my list. Is that a scheme you installed?

**Comment by jaiwardhan** [comment]
Yes. Just installed it using a jar.

**Comment by JacobAMason** [comment]
Ah. The xml is probably zipped inside the jar. Just unzip the jar file to find it.
