### ISSUE TITLE
Unable to load settings

### ISSUE THREAD

**Issue by theCanadianHat** [y3sh/Intellij-Colors-Sublime-Monokai#22]
After importing the settings through Intellij (14.1.4) and restarting I was prompted with this error message: Cannot read scheme SublimeMonokai.xml  from '$ROOT_CONFIG$/colors': Unsupported color scheme version: 142

I tried using the jar in the repo and building it through the shell script.

A friend of mine gave me an older version of the jar and it worked fine.
![intellij-setting-error](https://cloud.githubusercontent.com/assets/6870178/17490886/0b32d494-5d73-11e6-8b07-f49a7dd21231.png)

**Comment by wusandi** [comment]
I encoutered the same problem to you. And Have you solved it?

**Comment by y3sh** [comment]
Jetbrains changed the scheme formats between versions 14 and 16. I only have time to support the latest release. Consider trying my release back when 14 was out: https://github.com/y3sh/Intellij-Colors-Sublime-Monokai/commit/99b9dd8f05a659f81ebb0539c874040c8d2e02a3
