### ISSUE TITLE
new Constructor font color is Black on black

### ISSUE THREAD

**Issue by yofu1234** [y3sh/Intellij-Colors-Sublime-Monokai#23]
[![black on black](https://s22.postimg.org/xmd95iv1d/Screen_Shot_2016_11_16_at_4_06_39_PM.png)](https://postimg.org/image/477kwiqhp/)

People can't see the code when I show it to them and also its really hard to see unless I turn on my screen to full brightness.

Here is some code you can use to test:

```
var o = {};
o.constructor === Object; // true

var a = [];
a.constructor === Array; // true

var n = new Number(3);
n.constructor === Number; // true
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/constructor

tld;dr: Please change it to a different color.

**Comment by ggqq** [comment]
same problem.

**Comment by y3sh** [comment]
Which Jetbrains product and version are you using?

**Comment by yofu1234** [comment]
WebStorm, the newest version.

**Comment by y3sh** [comment]
Can't reproduce on OSX version of Webstorm 2016.3.3. Need more details.

<img width="780" alt="screen shot 2017-02-28 at 7 26 01 am" src="https://cloud.githubusercontent.com/assets/1032983/23406984/43c5bdb2-fd87-11e6-9c49-c0a6c02495cc.png">

**Comment by ggqq** [comment]
I am on Windows platform, with latest version of PyCharm.
