### ISSUE TITLE
Parameter hints are hard to read

### ISSUE THREAD

**Issue by nerzid** [y3sh/Intellij-Colors-Sublime-Monokai#24]
![image](https://cloud.githubusercontent.com/assets/11797282/25063298/36c2b332-21e9-11e7-8534-7ece2da17e6f.png)

Like here, **s_unit_type_name** parameter of the method **printSUnits** is really hard to read. Intellij Idea doesn't give us the option to change the color of this. [See post](http://stackoverflow.com/questions/13741939/change-foreground-color-of-parameter-info-in-intellij-editor).

**Comment by nerzid** [comment]
Oh, I've found the solution, If anyone has this issue, just change the foreground color of it in settings. 
![image](https://cloud.githubusercontent.com/assets/11797282/25063324/04d93750-21ea-11e7-82fb-44b357ca0ec6.png)

**Comment by y3sh** [comment]
Thanks for the find!
