### ISSUE TITLE
Error on importing the jar

### ISSUE THREAD

**Issue by brnrc** [y3sh/Intellij-Colors-Sublime-Monokai#3]
Error reading file 'C:\Users\Bruno\Downloads\SublimeMonoKai.jar'.
There was error in opening zip file

Please make sure you have generated the file using 'File|Export Settings' feature.

**Comment by uriklar** [comment]
I had the same error and my mistake was that I downloaded the file using "Save link as..." which downloaded an HTML file.. When I downloaded the actual file it all worked.
